/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 07-фев-2016 19:43:37 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `computers` CASCADE
;

DROP TABLE IF EXISTS `computer_vendors` CASCADE
;

DROP TABLE IF EXISTS `computer_types` CASCADE
;

DROP TABLE IF EXISTS `computer_providers` CASCADE
;

DROP TABLE IF EXISTS `components` CASCADE
;

/* Create Tables */

CREATE TABLE `computers`
(
	`computerid` INTEGER NOT NULL,
	`typeid` INTEGER 	 NULL,
	`computername` VARCHAR(50) 	 NULL,
	`computerprice` INTEGER 	 NULL,
	`balance` INTEGER 	 NULL,
	`vendorid` CHAR(10) 	 NULL,
	`providerid` CHAR(10) 	 NULL,
	CONSTRAINT `PK_computers` PRIMARY KEY (`computerid`)
)

;

CREATE TABLE `computer_vendors`
(
	`vendorid` CHAR(10) NOT NULL,
	`vendorname` VARCHAR(50) 	 NULL,
	`vendoraddress` VARCHAR(50) 	 NULL,
	`vendorphone` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_computer_vendors` PRIMARY KEY (`vendorid`)
)

;

CREATE TABLE `computer_types`
(
	`typeid` INTEGER NOT NULL,
	`typename` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_computer_types` PRIMARY KEY (`typeid`)
)

;

CREATE TABLE `computer_providers`
(
	`providerid` CHAR(10) NOT NULL,
	`providername` VARCHAR(50) 	 NULL,
	`provideraddress` VARCHAR(50) 	 NULL,
	`providerphone` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_computer_providers` PRIMARY KEY (`providerid`)
)

;

CREATE TABLE `components`
(
	`componentid` INTEGER NOT NULL,
	`computerid` INTEGER 	 NULL,
	`componentname` VARCHAR(50) 	 NULL,
	`componentnum` INTEGER 	 NULL,
	CONSTRAINT `PK_components` PRIMARY KEY (`componentid`)
)

;

/* Create Indexes, Uniques, Checks */

ALTER TABLE `computers` 
 ADD INDEX `IXFK_computers_computer_providers` (`providerid` ASC)
;

ALTER TABLE `computers` 
 ADD INDEX `IXFK_computers_computer_types` (`typeid` ASC)
;

ALTER TABLE `computers` 
 ADD INDEX `IXFK_computers_computer_vendors` (`vendorid` ASC)
;

ALTER TABLE `components` 
 ADD INDEX `IXFK_components_computers` (`computerid` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `computers` 
 ADD CONSTRAINT `FK_computers_computer_providers`
	FOREIGN KEY (`providerid`) REFERENCES `computer_providers` (`providerid`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `computers` 
 ADD CONSTRAINT `FK_computers_computer_types`
	FOREIGN KEY (`typeid`) REFERENCES `computer_types` (`typeid`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `computers` 
 ADD CONSTRAINT `FK_computers_computer_vendors`
	FOREIGN KEY (`vendorid`) REFERENCES `computer_vendors` (`vendorid`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `components` 
 ADD CONSTRAINT `FK_components_computers`
	FOREIGN KEY (`computerid`) REFERENCES `computers` (`computerid`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 ;
